[main]
git-src = "branch:main"

[develop]
git-src = "branch:develop"

[staging]
git-src = "branch:staging"

[develop_lair_0_1]
git-src = "branch:develop"
lair-version-req = "~0.1"

[v0_0_101] # broken
git-src = "revision:holochain-0.0.101"
lair-version-req = "~0.0"

[v0_0_102] # broken
git-src = "revision:holochain-0.0.102"
lair-version-req = "~0.0"

[v0_0_110]
git-src = "revision:holochain-0.0.110"
lair-version-req = "~0.0"
rust-version = "1.55.0"

[v0_0_115]
git-src = "revision:holochain-0.0.115"
lair-version-req = "~0.0"

[v0_0_116]
git-src = "revision:holochain-0.0.116"
lair-version-req = "~0.0"

[v0_0_117]
git-src = "revision:holochain-0.0.117"
lair-version-req = "~0.0"

[v0_0_118]
git-src = "revision:holochain-0.0.118"
lair-version-req = "~0.0"

[v0_0_119]
git-src = "revision:holochain-0.0.119"
lair-version-req = "~0.0"

[v0_0_120]
git-src = "revision:holochain-0.0.120"
lair-version-req = "~0.0"

[v0_0_121]
git-src = "revision:holochain-0.0.121"
lair-version-req = "~0.0"

[v0_0_122]
git-src = "revision:holochain-0.0.122"
lair-version-req = "~0.0"

[v0_0_123]
git-src = "revision:holochain-0.0.123"
lair-version-req = "~0.0"

[v0_0_124]
git-src = "revision:holochain-0.0.124"
lair-version-req = "~0.0"

[v0_0_125]
git-src = "revision:holochain-0.0.125"
lair-version-req = "~0.0"

[v0_0_126]
git-src = "revision:holochain-0.0.126"
lair-version-req = "~0.0"
