[nvfetcher]
fetch.github = "berberman/nvfetcher"
src.git = "https://github.com/berberman/nvfetcher"
src.branch = "master"

[crate2nix]
fetch.github = "kolloch/crate2nix"
src.git = "https://github.com/kolloch/crate2nix"

[nixpkgs]
src.git = "https://github.com/nixos/nixpkgs"
src.branch = "release-21.11"
fetch.github = "nixos/nixpkgs"

[rust-overlay]
src.git = "https://github.com/oxalica/rust-overlay"
fetch.git = "https://github.com/oxalica/rust-overlay"

[holochain_branch_develop]
src.branch = "develop"
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_9]
src.manual = "v0.0.9"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[lair_revision_v0_1_0]
src.manual = "v0.1.0"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_branch_main]
src.branch = "main"
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_110]
src.manual = "holochain-0.0.110"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_7]
src.manual = "v0.0.7"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_115]
src.manual = "holochain-0.0.115"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_116]
src.manual = "holochain-0.0.116"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_117]
src.manual = "holochain-0.0.117"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_118]
src.manual = "holochain-0.0.118"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_119]
src.manual = "holochain-0.0.119"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_120]
src.manual = "holochain-0.0.120"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_121]
src.manual = "holochain-0.0.121"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_122]
src.manual = "holochain-0.0.122"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_123]
src.manual = "holochain-0.0.123"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"
